[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.14.0",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "scapy>=2.6.1",
    "scikit-learn>=1.7.0",
    "streamlit>=1.46.0",
]
